server:
  port: 8761

eureka:
#  instance:
#    hostname: localhost
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/